services:
  frontend:
    image: ${REGISTRY}/${bNAME}
    ports:
      - "3000:80"
    networks:
      - my_network

  backend:
    image: ${REGISTRY}/${FNAME}
    ports:
      - "7000:7000"
    networks:
      - my_network


networks: 
  my_network:
    driver: bridge
