services:
  frontend:
    build: frontend/
    ports:
      - "3000:80"
    networks:
      - my_network

  backend:
    build: backend/
    ports:
      - "7000:7000"
    networks:
      - my_network


networks: 
  my_network:
    driver: bridge
