services:
  frontend:
    image: ${REGISTRY}/${FIMAGE}
    ports:
      - "3000:80"
    networks:
      - my_network

  backend:
    image: ${REGISTRY}/${BIMAGE}
    ports:
      - "7000:7000"
    networks:
      - my_network


networks: 
  my_network:
    driver: bridge
